### PR TITLE
add instructions for integrating with reg-core and reg-site

### PR DESCRIPTION
**Pull request by ascott1**
This adds some simplified instructions for how the three repos work together.

### CODE REVIEW

**Comment by cmc333333** [comment]
:+1: We'll sync these repos one way or another!

**Comment by ascott1** [comment]
Or get them wildly out of sync!

**Comment by willbarton** [comment]
:+1:

**Comment by khandelwal** [comment]
Nah, let's explore repo drift (I'm assuming movies like interstellar will be made by the time we're done)

**Comment by willbarton** [comment]
selfie-0

**Pull request merged**
