### PR TITLE
Add configuration to ignore subheaders in Appendixes

### PR DESCRIPTION
**Pull request by willbarton**
CFPB Regulation B has, in Appendix C, model forms that have within them subheaders that contain the strings 'Part I' and 'Part II'. These are "parts" of the model form, however, not the appendix itself. This adds configuration that will ignore a given subheader's label for structural purposes.

For example, given the following XML (directly from Reg B):

```xml
<HD SOURCE="HD1">Part I—Principal Reason(s) for Credit Denial, Termination, or Other Action Taken Concerning Credit</HD>
```

This configuration:

```python
APPENDIX_IGNORE_SUBHEADER_LABEL_1002 = {
    'C': ['I', 'II',],
}

APPENDIX_IGNORE_SUBHEADER_LABEL = {
    '1002': APPENDIX_IGNORE_SUBHEADER_LABEL_1002,
}
```

Will cause the parser to treat that XML node as an other header that did not contain 'Part I' in its text.

Possible concerns: It might be helpful to find a way to refer more specifically to particular node. Currently this would catch multiple `I` or `II` labels in appendix `C` if such exist.

### CODE REVIEW

**Comment by willbarton** [comment]
Reopening after I fixed the tests. Was running them locally on the wrong branch.

**Comment by cmc333333** [comment]
Something to ponder: would it make sense to insert a "don't mess with anything in here" tag into the xml?  The `<model_form>` tag? I'm not sure what all that would trigger, but I wonder how it stacks up against additional configurations

**Comment by willbarton** [comment]
@grapesmoker and I discussed something similar for a comparable problem, but we decided on configuration in order to avoid changing the XML too much. I think either approach would work, but my concern is that, ideally, configuration is clearable about what's it's doing than inserting new things into XML. But I think it's one or the other for some of the problems we're encountering — either adding structure in the XML or adding per-regulation configuration to express structure that's ambiguous in the XML.

**Comment by grapesmoker** [comment]
My prejudice is that, barring obvious XML errors like unclosed or incorrect tags, we should avoid changing the source XML. That kind of thing tends to become implicit which I think is worse than explicit workarounds that say "this section doesn't work, so here's some custom logic to get through that."

**Comment by cmc333333** [comment]
I definitely understand that argument. I've shifted to preferring XML changes because it limits the complexity for the configurer. We had (still have) the `MACROS_SOURCES` guy, which has the potential to move all XML edits into configurations. It was incredibly unreadable and mixed configurations with content, so we backed pretty far away from it in the end. It also made setting up the project a pain as there was effectively proprietary data (stored in a random config file) required to run the parser.

I wonder if it'd make sense to have a more global place to keep those sort of content-related tweaks. A shared database or repository of some sort. That'd be a good start for collapsing down the various types of content tweaks, too. Something else to ponder.

**Comment by willbarton** [comment]
It actually occurs to me that XML changes could have more granularity, differing across notices of the same regulation. 

I'd like to give this some more thought. I'll leave this PR here, since it's an extant fix for B's Appendix C, but I'd request that it not be merged right now.

**Comment by willbarton** [comment]
@cmc333333, @grapesmoker: So, would it make sense in this particular case to simply add an `ignore="true"` attribute to the element in XML and handle it that way?

**Comment by cmc333333** [comment]
My apologies; I didn't intend to be a stick in the mud! I think this PR, as it stands is good, and I certainly didn't mean to hold it up.

My comments were more about a more general issue. Where _should_ these things -- where the regulation, as presented, is not enough -- live? For example, the appendices of reg Z contain a bit of SAS code (yes), so we [added](https://github.com/cfpb/fr-notices/commit/68c556654b742a8a8ae92249f3ce46696ba0604c) a `CODE` tag. The upshot to putting tweaks/layering onto the regs this way is that there's only the two types of content -- the original and the modified. The downside is that you're manipulating regulations, which has obvious risks. It might make sense to have a regs attorney approve all changes, but given some of the more complex alterations (like splitting a notice), this probably isn't feasible. We settled for manual review by business analysts, but when we consider the size of the regulation, we know that that's not perfect.

The attribute idea is a good one, though I too worry about managing it across updates. Appendices are quite ugly, particularly around depth parsing and updates. We started to pull out the "Part" numbers (the ones you're trying to ignore) because there were later notices which referenced changes by part number. That may have just been too ambitious -- perhaps there should really only be a "this-is-a-model-form" tag and we make little attempt to pull out meaning from its contents. This would make updates to appendices more manual (though that's not a huge stretch).

**Pull request merged**
