### PR TITLE
Improved parser workflow

### PR DESCRIPTION
**Pull request by thejennywang**
Getting oldest version of a regulation is easier now because of this improved workflow hacked together during GovTechHack

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
Mind including the slides for the folks in DC?

**Comment by thejennywang** [comment]
Sure, here's the google doc link: https://docs.google.com/presentation/d/1KmKyd4Z-ECYQnLqCg-0RW9MjdfuSpHT5QpNQxAAvmRg

**Comment by ascott1** [comment]
:heart:'s all around. Thanks to everyone involved for working on this!

**Comment by cmc333333** [comment]
This is just https://github.com/18F/regulations-parser/pull/10 . @thejennywang should this be another branch?

**Comment by grapesmoker** [comment]
This is very nice, but I'm not sure if the profiling detailed in the last part of the presentation is the full story. Yes, build_notice eats a lot of the time, but it's not the actual building that's doing it. I spent a good deal of time profiling the parser, and what's really taking the vast majority of the time is the pyparsing code. It's just very, very slow. The other major consumer of time is the diffing code, which is significant only for regs that have lots of revisions.

I've been working intermittently on a C-based parser (implemented using flex and bison) that compiles down to a Python module. Right now this code lives on a personal repo rather than on any CFPB-owned ones. It doesn't implement the full grammar at this point, but what is implemented works pretty well. I think that performance improvements in parsing should move in the direction of replacing pyparsing; preliminary testing suggests that we could realize an improvement of several orders of magnitude by doing that.

**Comment by thejennywang** [comment]
@cmc333333 Before, getting the oldest version of a reg requires digging for a doc-number (example starred below) that takes a long time to find:
$ python build_from.py CFR-1997-title11-vol1-part110.xml 11 **96-20102** 5 552
Now, it's just
$ python build_from.py CFR-1997-title11-vol1-part110.xml 11 5 552

Much less painful!

@grapesmoker I didn't work on that part and the code from those members aren't included in the pull request. I could ask for it if you guys would like to see what was done anyway.

**Comment by grapesmoker** [comment]
@thejennywang I'd be definitely interested to see it.

**Comment by cmc333333** [comment]
Code in question is at https://github.com/18F/regulations-parser/pull/11 . We'll merge that after some tweaks, then pull in the cfpb changes (to fix the merge conflict).

We'll also need to update the README instructions (created in https://github.com/18F/regulations-parser/pull/10) with the new regulations-site build instructions.

**Pull request merged**
