### PR TITLE
Fixes for Reg B 1500: Unmarked Paragraphs

### PR DESCRIPTION
**Pull request by willbarton**
This PR fixes a couple issues encountered with Reg B relating to unmarked paragraphs.

In interpretations, Reg B has a introductory paragraph that is unmarked before other marked paragraphs. This situation is now handled by finding those sorts of paragraphs and attaching them to the heading node.

A similar problem happens in regulation text where a section has an unmarked paragraph followed by marked paragraphs. This is also handled in a similar manner.

### CODE REVIEW

**Comment by ascott1** [comment]
@grapesmoker to review

**Comment by willbarton** [comment]
I think this might be superseded by #299. We need to make sure though. Merge with caution.

**Comment by ascott1** [comment]
I ran this with my latest B parse (without #299) without issues. Though I didn't try it with any other regs.

**Comment by willbarton** [comment]
@ascott1 is this paragraph:

> Following is an official interpretation of Regulation B (12 CFR Part 1002) issued by the Bureau of Consumer Financial Protection. References are to sections of the regulation or the Equal Credit Opportunity Act (15 U.S.C. 1601 et seq.).

between the "Introduction" header and the numbered paragraphs in the Interpretations Introduction of B without this PR?

**Comment by willbarton** [comment]
Oh, and are you using that fix for unmarked paragraphs I gave you?

**Comment by ascott1** [comment]
> Oh, and are you using that fix for unmarked paragraphs I gave you?

I don't think so. I ran it as is from this branch.

> between the "Introduction" header and the numbered paragraphs in the Interpretations Introduction of B without this PR?

It is!

screen shot 2015-09-17 at 12 54 08 pm

**Comment by ascott1** [comment]
>  I ran it as is from this branch.

Well, merged with whatever is on master if this is behind that.

**Pull request closed without merging**
