### PR TITLE
Xml writer devel

### PR DESCRIPTION
**Pull request by grapesmoker**
This PR makes a few changes to the notice compiler in order to keep it from blowing up if it encounters some undefined nodes.

### CODE REVIEW

**Comment by willbarton** [comment]
We'll give it a shot.

**Comment by willbarton** [comment]
Oh, except this is kind of critical: `ImportError: cannot import name ucase_letters`

**Comment by grapesmoker** [comment]
oopsy daisy

fixed

**Comment by willbarton** [comment]
BAM!

**Pull request merged**
